spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 1000
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB   
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
logging:
  config: classpath:spring-log4j2.yml